### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [dajare/l-m-montgomery_the-blue-castle#1]
# Semantics

- [x] chapter-37: "Dear Miss S-t-*e*-r-l-i-n-g" is a case of [spelling out a word](https://standardebooks.org/manual/1.7.0/8-typography#8.2.8.2.1). In this case I think you would set all of the letters *except* the emphasized *e* with `<i epub:type="z3998:grapheme">` and format the *e* as `<span epub:type="z3998:grapheme">e</span>` (unitalicized for contrast),
- [x] chapter-5: Similar case with spelling "M-i-r-a-g-e." You also forgot to remove the `z3998:roman` semantic that was automatically added to the `i`.
- [x] chapter-38: You marked "B.A." as an initialism when it is an [academic degree](https://standardebooks.org/manual/1.7.0/8-typography#8.10.5), so it needs a `z3998:name-title` semantic.
- [x] chapter-32: "à la" is in [MW](https://www.merriam-webster.com/dictionary/%C3%A0%20la) so it doesn't need italics or `xml:lang` semantics.
- [x] chapter-35: "Was it possible Dr. Trent had made a mistake?" seems like an [italicized internal thought](https://standardebooks.org/manual/1.7.0/8-typography#8.2.7) so you should use `<q>` with italic styling instead.

# Typography

- [x] chapter-5: [This page](https://babel.hathitrust.org/cgi/pt?id=uva.x000134270&view=page&seq=44&q1=illusory) shows "mirage" and "marriage" both intentionally spelled with a hyphen (I assume to indicate the speaker's emphasis). It looks like the PG text dropped the hyphen in "marriage" for some reason, and then modernize-spelling took out the hyphen in "mirage." You should add those hyphens back.
- [x] chapter-42: I would remove the period after "Doc" and the abbreviation semantics in an editorial commit. ["Doc"](https://www.merriam-webster.com/dictionary/doc) is in MW as a normal word.

# Commit History

- [x] 0ccf71f7b2a63e3564eb974d82f86eaadd6476b7: Ligature changes should be marked as Editorial.
- [x] 24b7d978bf436d193b51dc7c86d7ebcbd2b94275, fe02edf4aad523c59d585382dcf6a80d8ac71935: Removing italics is just changing formatting, which doesn't need to be Editorial.

# Lint

- [x] I think the t-003 lint check (`What is the difference between Doss and a mouse?`) is a [false positive](https://babel.hathitrust.org/cgi/pt?id=uva.x000134270&view=page&seq=21&q1=difference), so you can create an `se-lint-ignore.xml` file for that.
- [x] For the t-005 lint check (`herself” they said`), I think the [printed text](https://babel.hathitrust.org/cgi/pt?id=uva.x000134270&view=page&seq=121&q1=resentfully) reads rather awkwardly and I would add a comma after "herself" in an editorial commit to correct that.

**Comment by dajare** [comment]
Splendid review, Weijia. I'm sorry (a) I forgot to add production notes on those lint errors; and (b) I left so much for you to discover!

I think (hope) that's all cleaned up now.

**Comment by dajare** [comment]
> Thanks! Just one last thing, my interpretation was that the "M-i-r-a-g-e" in chapter 5 is an case of spelling, so the individual letters need `<i epub:type="z3998:grapheme">` like the "S-t-_e_-r-l-i-n-g" case.

Of course! Sorry. Will do that now. I blame it on this tropical heat addling my brain. 🥵
